apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.isstateful }}  
  clusterIP: None
{{- end }}
  ports:
{{- range $port := .Values.ports }}
  - name:  {{ $port.name }}
    port: {{ $port.externalPort }}
    targetPort: {{ $port.internalPort }}
    protocol: TCP
{{- end }}
  selector:
    app: {{ template "fullname" . }}
