{{- if .Values.isstateful -}}
{{- $root := . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      draft: {{ default "draft-app" .Values.draft }}
      app: {{ template "fullname" . }}
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      terminationGracePeriodSeconds: 1800
      volumes:
{{- range $i, $volume := .Values.volumes }}
        - name: vol-{{ $root.Values.service.name }}-{{$i}}
          persistentVolumeClaim:
            claimName: pvc-{{ $root.Values.service.name }}-{{$i}}
{{- end }}      
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ .Values.service.name }}-config
          - secretRef:
              name: {{ .Values.service.name }}-secret
        ports:
{{- range $port := .Values.ports }}
        - containerPort: {{ $port.internalPort }}
{{- end }}
        volumeMounts:
{{- range $i, $volume := .Values.volumes }}      
          - mountPath: "{{ $volume.mountPath }}"
            name: vol-{{ $root.Values.service.name }}-{{$i}}
{{- end }}        
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end -}}
